### ISSUE TITLE
Few items to be re-organized

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#450]
- [x] ~~boxcryptor from "other" to "backup and sync" as its a dropbox  copycat with end to end encryption.~~ Handled in #424 
- [x] ~~Doordash from other to food as its a food service similar to Blue Apron~~ Handled in #424 
- [x] ~~BasisCode Compliance from other to developer? @joshmcintyre can you help with a verdict on this one?~~ Handled in #424 
- [x] Evaluate some 'Other' section items to see if we can separate them into already defined sections. A lot of them are just carry-overs from the 2factorauth site we forked at the beginning of the project and we've added new sections since then and havent gone to the 'Other' section to re-evaluate things
- [x] Move Cryptonize.it from retail to crypto-service
- [x] Purse also should be moved from retail to crypto-service, its really just a pure crypto-service
- [x] Move 'Webroot' from Security to anti-virus.
- [x] Remove additional Norton listing from security section since its in antivirus section now.

**Comment by kenman345** [comment]
Please add items to the list if you have any findings.

**Comment by joshmcintyre** [comment]
Those first three list items I agree with.

- boxcryptor is a good fit for backup and sync
- Doordash belongs in food
- BasisCode should be a good fit for developer

I have some other ideas - we should consider adding a "BitcoinCash/Crypto Swag" section (with a better name of course, open to ideas) to get some of the crypto sticker and shirt sites out of retail and into something more specific. There are several sites selling BCH stickers, shirts, etc. that could form their own section.

**Comment by kenman345** [comment]
I’d be good with that, but we need to find the right icon for such a
section. I’ll look tomorrow

**Comment by kenman345** [comment]
I will rename issue #424 then to reflect the agreed change and include the other moving around in that as well so we can use this issue to discuss any other findings as we look through the bloated sections to see if any other moves make sense.

**Comment by kenman345** [comment]
- [ ] Move Cryptonize.it from retail to crypto-service

Cryptonize it is similar to giftoff, egfiter and gyft, so it belongs with them instead of cluttering up retail.

**Comment by kenman345** [comment]
- [ ] Purse also should be moved, its really just a pure crypto-service

**Comment by kenman345** [comment]
- [ ] Move 'Webroot' from Security to anti-virus.

- [ ] Remove additional Norton listing from security section since its in antivirus section now.

**Comment by t0p0lin0** [comment]
I'll try to remember to take care of the remaining ...

- [ ] Evaluate some 'Other' section items to see if we can separate them into already defined sections. A lot of them are just carry-overs from the 2factorauth site we forked at the beginning of the project and we've added new sections since then and havent gone to the 'Other' section to re-evaluate things

...task during the refactoring of page template code/includes.

**Comment by kenman345** [comment]
I think we've done a good job of satisfying everything in this ticket. I'm closing it out
